package com.github.tukcps.sysmd.model.generator.kotlin

import com.github.tukcps.sysmd.model.generator.GeneratorConfiguration

/**
 * Writes Kotlin source code.
 */
class KotlinWriter {

    private val builder = StringBuilder()
    private var indentation = 0

    override fun toString(): String =
        builder.toString()

    /**
     * Writes one line.
     *
     * @param text Line to write.
     */
    fun line(text: String = "") {
        repeat(indentation) { builder.append("    ") }
        builder.appendLine(text)
    }

    /**
     * Increases the indentation.
     */
    fun indent() {
        indentation++
    }

    /**
     * Decreases the indentation.
     */
    fun unindent() {
        require(indentation > 0)
        indentation--
    }

    /**
     * Begins a Kotlin block.
     *
     * @param header Block header.
     */
    fun begin(header: String) {
        line("$header {")
        indent()
    }

    /**
     * Ends a Kotlin block.
     */
    fun end() {
        unindent()
        line("}")
    }

    /**
     * Writes a KDoc comment.
     *
     * @param lines Comment lines.
     */
    fun kdoc(vararg lines: String) {

        line("/**")

        lines.forEach {
            if (it.isEmpty())
                line(" *")
            else
                line(" * $it")
        }

        line(" */")
    }

    /**
     * Writes import statements.
     *
     * @param imports Fully qualified imports.
     */
    fun imports(vararg imports: String) {

        imports
            .sorted()
            .forEach { line("import $it") }

        if (imports.isNotEmpty())
            line()
    }

    /**
     * Writes the standard header for generated Kotlin source files.
     *
     * @param generator Name of the generating class.
     */
    fun generatedFile(generator: String) {

        kdoc(
            "GENERATED FILE - DO NOT EDIT.",
            "",
            "Generated by $generator.",
            "Source: ${GeneratorConfiguration.KERML_SOURCE}",
            "Source: ${GeneratorConfiguration.SYSML_SOURCE}",
            "Version: ${GeneratorConfiguration.VERSION}",
            "",
            "Any manual changes will be lost the next time the generator is executed."
        )
    }

    /**
     * Writes a package declaration.
     *
     * @param packageName Kotlin package name.
     */
    fun packageDeclaration(
        packageName: String
    ) {
        line("package $packageName")
        line()
    }
}