/**
 * GENERATED FILE - DO NOT EDIT.
 *
 * Generated by MissingInterfaceGenerator.
 * Source: https://www.omg.org/spec/KerML/20250201/KerML.xmi
 * Source: https://www.omg.org/spec/SysML/20250201/SysML.xmi
 * Version: 20250201
 *
 * Any manual changes will be lost the next time the generator is executed.
 */

package com.github.tukcps.sysmd.model.kerml

interface ElementFilterMembership : OwningMembership {
}
