package com.github.tukcps.sysmd.model.expression.functions

import io.github.tukcps.aadd.*
import com.github.tukcps.sysmd.exceptions.SemanticError
import com.github.tukcps.sysmd.model.expression.AstNode
import com.github.tukcps.sysmd.quantities.Quantity
import com.github.tukcps.sysmd.quantities.VectorQuantity
import com.github.tukcps.sysmd.quantities.ite
import com.github.tukcps.sysmd.services.session.Session

/**
 * The ITE function.
 * It uses lazy evaluation and takes three parameters:
 * - the first parameter is of type Bool.
 * - the second and third parameters are of arbitrary but equal type.
 * The result of the ITE function is the second parameter if the first is true,
 * else the third.
 */
class AstIte(model: Session, args: ArrayList<AstNode>) :
    AstFunction("ITE", model, 3, args) {

    override fun initialize() {
        if (!parameters[0].isBool)
            throw SemanticError("ITE Function call, expected: 1st parameter of type BOOL, got: ${parameters[0].upQuantity}")

        /* Type checking here only at run-time. */
        when (parameters[1].upQuantity.values[0]) {
            is BDD -> {
                if (parameters[2].upQuantity.values[0] !is BDD)
                    throw SemanticError("Expect 3rd parameter of ite function of type Bool")
                upQuantity = VectorQuantity(mutableListOf(model.builder.Bool))
            }

            is IDD -> {
                if (parameters[2].upQuantity.values[0] !is IDD)
                    throw SemanticError("Expect 3rd parameter of ite function of type Int")
                upQuantity = VectorQuantity(mutableListOf(model.builder.Integers))
            }

            is AADD -> {
                if (parameters[2].upQuantity.values[0] !is AADD)
                    throw SemanticError("Expect 3rd parameter of ite function of type Bool")
                upQuantity = VectorQuantity(mutableListOf(model.builder.Reals), "?")
            }

            is StrDD -> {
                if (parameters[2].upQuantity.values[0] !is StrDD)
                    throw SemanticError("Expect 3rd parameter of ite function of type String")
                upQuantity = VectorQuantity(mutableListOf(model.builder.Strings))
            }

            else -> throw SemanticError("ITE function only for Bool, AADD, StrDD and IDD defined")
        }
        evalUp()
        downQuantity = upQuantity.clone()
    }

    /**
     * Here we just pass the 2nd or 3rd parameter up. the 1st is evaluated in evalUpRec.
     */
    override fun evalUp() {
        try{
            upQuantity = getBDDParam(0).upQuantity.bdd().ite(
                getParam(1).upQuantity,
                getParam(2).upQuantity
            )
        } catch (e: Exception) {
            throw SemanticError("ITE function: ${e.message}")
        }
    }


    /**
     * ITE function with parameters with lazy evaluation.
     * We first evaluate the 1st parameter.
     * If it is true, the 2nd is evaluated.
     * if not, the 3rd is evaluated.
     * if the first parameter is both true and false, 2nd and 3rd are evaluated, and
     * the result is represented as a symbolic ITE representation in evalUp.
     */
    @Throws(SemanticError::class)
    override fun evalUpRec() {
        getParam(0).evalUpRec()
        // We do no lazy evaluation.
        getBDDParam(0)
        getParam(1).evalUpRec()
        getParam(2).evalUpRec()
        // now do ITE function.
        evalUp()
    }


    /**
     * ITE function from the result downwards computation.
     * As we work on BDD for the digital side that are generated by evalUp, evalDown does nothing.
     */
    override fun evalDown() {
        if(downQuantity == getParam(1).upQuantity)
            getParam(0).downQuantity = Quantity(downQuantity.value.builder.True)
    }

    /** Executes a block of statements on each AstNode in an Ast */
    override fun <T> runDepthFirst(block: AstNode.() -> T): T {
        for (p in parameters)
            p.runDepthFirst(block)
        return run(block)
    }

    override fun clone(): AstIte {
        val parClone = ArrayList<AstNode>()
        for (p in parameters) parClone.add(p.clone())
        return AstIte(model, parClone)
    }
}
