[versions]
kotlin = "2.4.0"
compose-plugin = "1.11.1"
compose = "1.11.1"
ui-graphics-desktop = "1.7.0"

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-ui-test = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "compose" }
compose-ui-test-junit4 = { module = "org.jetbrains.compose.ui:ui-test-junit4", version.ref = "compose" }
ui-graphics-desktop = { group = "androidx.compose.ui", name = "ui-graphics-desktop", version.ref = "ui-graphics-desktop" }