package com.github.tukcps.sysmd.model.kerml.implementation

import com.github.tukcps.sysmd.model.generated.elementType
import com.github.tukcps.sysmd.model.kerml.*
import com.github.tukcps.sysmd.model.util.QualifiedName
import com.github.tukcps.sysmd.model.util.SimpleName
import com.github.tukcps.sysmd.services.session.Session
import kotlin.uuid.Uuid

/**
 * Base class for the repository entities.
 * Elements can be of the special kind Package.
 * Elements are
 * - identified by a unique id field,
 * - have a user-given identification following the KerML v2 rules,
 * - a list of imports following SysML rules,
 * - a collection of owned elements that may not be identified by its names (then we would need a namespace)
 *   @param elementId a UUID v4 that is valid for the overall life cycle (versions) of an element.
 *                    Default is UUID4.
 *   @param declaredName a simple name
 *   @param declaredShortName a simple name that abbreviates the name
 *   @param aliasIds a tool-specific set of alias ids
 *   @param owningRelationship the memberships; must be resolved in case of standard libraries to get UUID5 based on qualified name
 */
open class ElementImplementation(
    final override val model: Session,
    final override val elementId: Uuid = Uuid.random(),
    final override var declaredName: SimpleName? = null,
    final override var declaredShortName: SimpleName? = null,
    final override var aliasIds: Collection<String> = emptyList(),
    override var ownedRelationship: MutableList<Relationship> = mutableListOf(),
    final override var owningRelationship: OwningMembership? = null,
    final override var textualRepresentation: MutableList<TextualRepresentation> = mutableListOf(),
    final override var documentation: MutableList<Documentation> = mutableListOf(),
    final override var isImpliedIncluded: Boolean = false,
 ) : Element {
    override val name: SimpleName?
        get() = declaredName

    override val shortName: SimpleName?
        get() = declaredShortName

    /** Field-less property that gets the owning namespace. */
    override val owningNamespace: Namespace?
        get() = owner.let { it as? Namespace ?: it?.owningNamespace }

    /** Field-less property that gets the owning standard-namespace or null if not standard. */
    final override val standardNamespace: Namespace?
        get() = owningRelationship?.owner?.let {
            if (it is Namespace && it.isStandard) it else it.standardNamespace
        }

    /** Field that is true for a library element, then all owned elements are library elements */
    final override val isLibraryElement: Boolean
        get() = this is LibraryPackage ||
                (owningNamespace?.isLibraryElement == true) ||
                (owner?.isLibraryElement == true) ||
                (this is Membership && this.memberElement.isLibraryElement)

    /** Field that is true if the element is owned by a standard library */
    override var isStandard: Boolean = false
        get() = field || (owningNamespace?.isStandard == true)

    final override var isTransient: Boolean = false

    /** The input of the compiler that generated the element */
    final override var input: CharSequence? = null

    /** The range of the input by which it was generated */
    final override var indices: IntRange? = null

    /**
     * Flag that is set if some non-transient information was changed.
     * Then, a new id is needed before persisting the element in the backend.
     */
    final override var hasBeenChanged: Boolean = false

    /**
     * Whether value has been changed by constraint propagation.
     * As this affects only non-transient information, no new id is needed.
     */
    final override var updated: Boolean = true


    /** Field-less property; name + owner's name determines qualified name. */
    final override val qualifiedName: QualifiedName?
        get() = when {
            this == model.global -> null
            this.owningNamespace == model.global -> escapedName()
            else -> escapedName()?.let { en ->
                owner?.qualifiedName?.let { on ->
                    "$on::$en"
                }
            }
        }

    /**
     * Complementary to qualified name; also considers the case that an element has no name.
     * The path uses the qualified name, iff possible; else, the indexes in the owns relations.
     * In deviation to the standard, we do NOT use index in the path of memberships if names are available.
     * The reason is index also includes the ordering of the usage of standard packages which then has impact on the UUID5
     * generated by the path.
     */
    final override fun path(): String = when {
        qualifiedName !== null -> qualifiedName!!

        this is Relationship && this !is Namespace && this !is AnnotatingElement
            -> owningRelatedElement.path() + "/" + (this.owningRelatedElement.positionOf(this)!!+1)

        owningRelationship !== null
            -> owningRelationship!!.path() + "/" + (this.owningRelationship!!.positionOf(this)!!+1)

        else -> ""
    }

    /**
     * The index of the element in the list of owned elements resp. relationships.
     * Returns the total number of owned elements if the given element isn't owned
     * (i.e. its position if it were to be inserted)
     */
    final override fun positionOf(element: Element): Int
    = ownedRelationship.indexOfFirst {
            it === element || (it is OwningMembership && it.memberElement === element)
        }.let {
            if(it < 0) ownedRelationship.size else it
        }

    override fun toString(): String = "[${elementType().name}] " +
            if (escapedName() == null) "" else "'${escapedName()}'"

    /**
     * Clone creates a copy of all fields, but NOT of the owned elements;
     * only some well-understood owned elements from the metamodel are copied (e.g., Multiplicity, ...).
     * Hence, the consistency of the model is NOT by itself preserved.
     * Function should NOT be used to copy parts of the model;
     * ONLY to create a backup or in really internal logic when there are no or well-understood owned elements.
     * !!! TAKE CARE !!!
     * Also, the clone is given a new id.
     */
    override fun clone(): Element = ElementImplementation(
        model,
        declaredName = declaredName,
        declaredShortName = declaredShortName,
    ).also {
        it.updateFrom(this)
    }

    /**
     * Simply copies all fields from a template into the current element.
     * Note that only a shallow copy is made, no deep copy.
     * Also note that the id of the original element is NOT copied.
     * @param template the template whose fields will be copied.
     */
    override fun updateFrom(template: Element) {
        if (declaredName != template.declaredName) {
            declaredName = template.declaredName
        }
        if (declaredShortName != template.declaredShortName) {
            declaredShortName= template.declaredShortName
        }
        if (aliasIds != template.aliasIds) {
            aliasIds = template.aliasIds
        }
        isTransient = template.isTransient
        hasBeenChanged = template.hasBeenChanged
        isStandard = template.isStandard
        input = template.input?:input
        indices = template.indices?:indices
        input = template.input
        indices = template.indices?:indices
    }

    /** A useful name, lexically correct, generated from name or short name */
    override fun escapedName(): String? = name?:shortName
    override fun effectiveName(): String? = declaredName
    override fun effectiveShortName(): String? = declaredShortName
}
