/**
 * GENERATED FILE - DO NOT EDIT.
 *
 * Generated by MissingImplementationGenerator.
 * Source: https://www.omg.org/spec/KerML/20250201/KerML.xmi
 * Source: https://www.omg.org/spec/SysML/20250201/SysML.xmi
 * Version: 20250201
 *
 * Any manual changes will be lost the next time the generator is executed.
 */

package com.github.tukcps.sysmd.model.kerml.implementation

import com.github.tukcps.sysmd.model.kerml.*
import com.github.tukcps.sysmd.services.session.Session
import kotlin.uuid.Uuid

/** Suggested implementation superclass: ConnectorImplementation. */
class FlowImplementation(model : Session,elementId : Uuid = Uuid.random()) :
    Flow, ConnectorImplementation(model,elementId = elementId)
{
    val flowEnd: MutableList<FlowEnd> = TODO()
    val interaction: MutableList<Interaction> = TODO()
    val payloadFeature: PayloadFeature? = TODO()
    val payloadType: MutableList<Classifier> = TODO()
    val sourceOutputFeature: Feature? = TODO()
    val targetInputFeature: Feature? = TODO()
}
