package com.github.tukcps.sysmd.compiler.scanner


/**
 * We represent tokens by this enum. The enum also has properties sVal and nVal in
 * which the string or numeric value of literals is saved.
 * @param kind the kind of token, as defined below
 * @param string the text of the token
 * @param number the value of the token, if it is a number, as a Real
 * @param lineNo the line number in which the token started
 * @param indices the indices of the token in the input stream, as first .. last character range
 **/
class Token(
    val kind: Kind,
    val string: String,
    val number: Double = 0.0,
    val lineNo: Int = 0,
    val indices: IntRange = 0 .. 0
) {

    override fun toString(): String = when (kind) {
        Kind.NAME_LIT -> string
        Kind.INTEGER_LIT -> number.toString()
        Kind.STRING_LIT -> "\"$string\""
        else -> kind.toString()
    }

    /**
     * An enumeration of all token's kind
     */
    enum class Kind {
        // Just for passing information; not really tokens
        ERROR, WHITESPACE, COMMENT,

        // Literals
        INTEGER_LIT, FLOAT_LIT, STRING_LIT, NAME_LIT,

        // SysML & SysMD Keywords for Types and Identification
        DEFINES, ONE, HAS_A,

        // SysML & KerML Keywords
        ABOUT, ABSTRACT, ACCEPT, ACTION, ACTOR, AFTER, ALIAS, ALL, ALLOCATION, ALLOCATE, ANALYSIS, AS, ASSOC, ASSERT, ASSIGN, ASSUME, AT, ATTRIBUTE,
        BEHAVIOR, BIND, BINDING, BLOCK, BOOL, BY,
        CALC, CASE, CHAINS, CLASS, CLASSIFIER, CONCERN, CONJUGATE, CONJUGATES, CONNECT, CONST, COMPOSITE, CONJUGATION, CONNECTION, CONNECTOR, CONSTRAINT, CROSSES,
        DATATYPE, DECISION, DEF, DEFAULT, DO, DOC, DECIDE, DEFINED, DEPENDENCY, DERIVED, DIFFERENCES, DISJOINT, DISJOINING,
        ELSE, END, ENTRY, ENUM, EVENT, EXHIBIT, EXIT, EXPR, EXPOSE,
        FIRST, FEATURE, FEATURED, FEATURING, FILTER, FLOW, FOR, FORK, FRAME, FROM, FUNCTION,
        HASTYPE,
        IF, IMPORT, IN, IMPLIES, INCLUDE, INDIVIDUAL, INOUT, INTERACTION, INTERFACE, INTERSECTS, INV, INVERSE, INVERTING, ISTYPE, ITEM,
        JOIN,
        LANGUAGE, LIBRARY, LOOP,
        MEMBER, METADATA, MERGE, MESSAGE, METACLASS, MULTIPLICITY,
        NAMESPACE, NONUNIQUE, NOTE, NULL,
        OBJECTIVE, OCCURRENCE, OF, ORDERED, OUT,
        PACKAGE, PARALLEL, PART, PERFORM, PORT, PORTION, PREDICATE, PRIVATE, PROTECTED, PUBLIC,
        READONLY, REF, REGULAR_COMMENT, RELATIONSHIP, RENDER, RENDERING, REQUIRE, REP, RETURN, REDEFINES, REDEFINITION, REFERENCES, REQUIREMENT,
        SATISFY, SEND, SNAPSHOT, SPECIALIZATION, SPECIALIZES, STAKEHOLDER, STANDARD, STATE, STEP, STRUCT, STRUCTURE, SUBCLASSIFIER, SUBSET, SUBJECT, SUCCESSION, SUBSETS, SUBTYPE,
        TERMINATE, THEN, TIMESLICE, TO, TRANSITION, TYPE, TYPED, TYPING,
        UNIQUE, UNIONS, USE, UNTIL,
        VAR, VARIANT, VARIATION, VERIFICATION, VERIFY, VIA, VIEW, VIEWPOINT,
        WHEN, WHILE,
        XOR,

        // Operators
        LCURBRACE { override fun toString() = "{" },
        RCURBRACE { override fun toString() = "}" },
        GT { override fun toString() = ">" },
        LT { override fun toString() = "<" },
        GE { override fun toString() = ">=" },
        LE { override fun toString() = "<=" },
        EE { override fun toString() = "==" },
        DPEQ { override fun toString() = ":=" },
        DPGT { override fun toString() = ":>" },
        NEQ { override fun toString() = "!=" },
        EOF { override fun toString() = "EOF" },
        DOTDOT { override fun toString() = ".." },
        TRUE { override fun toString() = "true" },
        FALSE { override fun toString() = "false" },
        EQ { override fun toString() = "=" },
        PLUS { override fun toString() = "+" },
        MINUS { override fun toString() = "-" },
        ARROW { override fun toString() = "->" },
        TIMES { override fun toString() = "*" },
        STARSTAR { override fun toString() = "**" },
        CROSS { override fun toString() = "cross" }, //For cross product
        DOTProduct { override fun toString() = "dot" }, //For cross product
        DIV { override fun toString() = "/" },
        DPDP { override fun toString() = "::" },
        EXP { override fun toString() = "^" },
        AND { override fun toString() = "and" },
        OR { override fun toString() = "or" },
        NOT { override fun toString() = "not" },
        LBRACE { override fun toString() = "(" },
        RBRACE { override fun toString() = ")" },
        LCBRACE { override fun toString() = "[" },
        RCBRACE { override fun toString() = "]" },
        DOT { override fun toString() = "." },
        COMMA { override fun toString() = "," },
        TYPED_BY { override fun toString() = ":" },
        SEMICOLON { override fun toString() = ";" },
        HASHTAG { override fun toString(): String = "#" },
        PERCENT { override fun toString(): String = "%" },
        EURO { override fun toString(): String = "€" },
        QUESTION { override fun toString(): String = "?" }
    }

    /** Constants for abbreviating some keywords */
    companion object Definitions {

        val WHITESPACE = setOf(' ', '\t', '\n', '\r', 13.toChar())

        val charTokens: HashMap<Char, Kind> = hashMapOf(
            '@' to Kind.METADATA,
            '(' to Kind.LBRACE,
            ')' to Kind.RBRACE,
            '[' to Kind.LCBRACE,
            ']' to Kind.RCBRACE,
            '{' to Kind.LCURBRACE,
            '}' to Kind.RCURBRACE,
            '=' to Kind.EQ,
            '+' to Kind.PLUS,
            '-' to Kind.MINUS,
            '*' to Kind.TIMES,
            '^' to Kind.EXP,
            '&' to Kind.AND,
            '|' to Kind.OR,
            '/' to Kind.DIV,
            '<' to Kind.LT,
            '>' to Kind.GT,
            'x' to Kind.CROSS,
            '.' to Kind.DOT,
            ',' to Kind.COMMA,
            ':' to Kind.TYPED_BY,
            ';' to Kind.SEMICOLON,
            '#' to Kind.HASHTAG,
            '%' to Kind.PERCENT,
            '€' to Kind.EURO,
            '?' to Kind.QUESTION,
            '~' to Kind.NOT,
            '!' to Kind.NOT
        )

        val additionalKeywords = hashMapOf(
            "cross" to Kind.CROSS,
            "dot" to Kind.DOTProduct
        )

        val kerMLKeywords = hashMapOf(
            "about" to Kind.ABOUT,
            "abstract" to Kind.ABSTRACT,
            "alias" to Kind.ALIAS,
            "all" to Kind.ALL,
            "and" to Kind.AND,
            "as" to Kind.AS,
            "assoc" to Kind.ASSOC,
            "behavior" to Kind.BEHAVIOR,
            "binding" to Kind.BINDING,
            "bool" to Kind.BOOL,
            "by" to Kind.BY,
            "chains" to Kind.CHAINS,
            "class" to Kind.CLASS,
            "classifier" to Kind.CLASSIFIER,
            "comment" to Kind.COMMENT,
            "composite" to Kind.COMPOSITE,
            "conjugate" to Kind.CONJUGATE,
            "conjugates" to Kind.CONJUGATES,
            "conjugation" to Kind.CONJUGATION,
            "connector" to Kind.CONNECTOR,
            "const" to Kind.CONST,
            "crosses" to Kind.CROSSES,
            "datatype" to Kind.DATATYPE,
            "default" to Kind.DEFAULT,
            "dependency" to Kind.DEPENDENCY,
            "derived" to Kind.DERIVED,
            "differences" to Kind.DIFFERENCES,
            "disjoining" to Kind.DISJOINING,
            "disjoint" to Kind.DISJOINT,
            "doc" to Kind.DOC,
            "else" to Kind.ELSE,
            "end" to Kind.END,
            "expr" to Kind.EXPR,
            "false" to Kind.FALSE,
            "feature" to Kind.FEATURE,
            "featured" to Kind.FEATURED,
            "featuring" to Kind.FEATURING,
            "filter" to Kind.FILTER,
            "first" to Kind.FIRST,
            "flow" to Kind.FLOW,
            "for" to Kind.FOR,
            "from" to Kind.FROM,
            "function" to Kind.FUNCTION,
            "hastype" to Kind.HASTYPE,
            "if" to Kind.IF,
            "intersects" to Kind.INTERSECTS,
            "implies" to Kind.IMPLIES,
            "import" to Kind.IMPORT,
            "in" to Kind.IN,
            "inout" to Kind.INOUT,
            "interaction" to Kind.INTERACTION,
            "inv" to Kind.INV,
            "inverse" to Kind.INVERSE,
            "inverting" to Kind.INVERTING,
            "istype" to Kind.ISTYPE,
            "language" to Kind.LANGUAGE,
            "library" to Kind.LIBRARY,          // Missing in standard, bug?
            "member" to Kind.MEMBER,
            "metaclass" to Kind.METACLASS,
            "metadata" to Kind.METADATA,
            "multiplicity" to Kind.MULTIPLICITY, // todo: fix name of function that gets multiplicity
            "namespace" to Kind.NAMESPACE,
            "nonunique" to Kind.NONUNIQUE,
            "not" to Kind.NOT,
            "null" to Kind.NULL,
            "of" to Kind.OF,
            "or" to Kind.OR,
            "ordered" to Kind.ORDERED,
            "out" to Kind.OUT,
            "package" to Kind.PACKAGE,
            "portion" to Kind.PORTION,
            "predicate" to Kind.PREDICATE,
            "private" to Kind.PRIVATE,
            "protected" to Kind.PROTECTED,
            "public" to Kind.PUBLIC,
            "readonly" to Kind.READONLY,            // Missing in standard -- bug?
            "redefines" to Kind.REDEFINES,
            "redefinition" to Kind.REDEFINITION,
            "references" to Kind.REFERENCES,
            "rep" to Kind.REP,
            "return" to Kind.RETURN,
            "specialization" to Kind.SPECIALIZATION,
            "specializes" to Kind.SPECIALIZES,
            "standard" to Kind.STANDARD,            // Missing in standard -- bug?
            "step" to Kind.STEP,
            "struct" to Kind.STRUCT,
            "subclassifier" to Kind.SUBCLASSIFIER,
            "subset" to Kind.SUBSET,
            "subsets" to Kind.SUBSETS,
            "subtype" to Kind.SUBTYPE,
            "succession" to Kind.SUCCESSION,
            "then" to Kind.THEN,
            "to" to Kind.TO,
            "true" to Kind.TRUE,
            "type" to Kind.TYPE,
            "typed" to Kind.TYPED,
            "typing" to Kind.TYPING,
            "unions" to Kind.UNIONS,
            "var" to Kind.VAR,
            "xor" to Kind.XOR,
        ) + additionalKeywords

        val sysMLv2Keywords = hashMapOf(
            "about" to Kind.ABOUT,
            "abstract" to Kind.ABSTRACT,
            "accept" to Kind.ACCEPT,
            "action" to Kind.ACTION,
            "actor" to Kind.ACTOR,
            "after" to Kind.AFTER,
            "alias" to Kind.ALIAS,
            "all" to Kind.ALL,
            "allocate" to Kind.ALLOCATE,
            "allocation" to Kind.ALLOCATION,
            "analysis" to Kind.ANALYSIS,
            "and" to Kind.AND,
            "as" to Kind.AS,
            "assign" to Kind.ASSIGN,
            "assert" to Kind.ASSERT,
            "assoc" to Kind.ASSOC,
            "assume" to Kind.ASSUME,
            "at" to Kind.AT,
            "attribute" to Kind.ATTRIBUTE,
            "bind" to Kind.BIND,
            "binding" to Kind.BINDING,
            "block" to Kind.BLOCK,
            "by" to Kind.BY,
            "calc" to Kind.CALC,
            "case" to Kind.CASE,
            "comment" to Kind.COMMENT,
            "concern" to Kind.CONCERN,
            "connect" to Kind.CONNECT,
            "connection" to Kind.CONNECTION,
            "constraint" to Kind.CONSTRAINT,
            "crosses" to Kind.CROSSES,
            "decide" to Kind.DECIDE,
            "def" to Kind.DEF,
            "default" to Kind.DEFAULT,
            "defined" to Kind.DEFINED,
            "dependency" to Kind.DEPENDENCY,
            "derived" to Kind.DERIVED,
            "do" to Kind.DO,
            "doc" to Kind.DOC,
            "else" to Kind.ELSE,
            "end" to Kind.END,
            "entry" to Kind.ENTRY,
            "enum" to Kind.ENUM,
            "event" to Kind.EVENT,
            "exhibit" to Kind.EXHIBIT,
            "exit" to Kind.EXIT,
            "expose" to Kind.EXPOSE,
            "false" to Kind.FALSE,      // Missing in standard
            "filter" to Kind.FILTER,
            "first" to Kind.FIRST,
            "flow" to Kind.FLOW,
            "for" to Kind.FOR,
            "fork" to Kind.FORK,
            "frame" to Kind.FRAME,
            "from" to Kind.FROM,
            "hastype" to Kind.HASTYPE,
            "if" to Kind.IF,
            "implies" to Kind.IMPLIES,
            "import" to Kind.IMPORT,
            "in" to Kind.IN,
            "include" to Kind.INCLUDE,
            "individual" to Kind.INDIVIDUAL,
            "inout" to Kind.INOUT,
            "interface" to Kind.INTERFACE,
            "istype" to Kind.ISTYPE,
            "item" to Kind.ITEM,
            "join" to Kind.JOIN,
            "language" to Kind.LANGUAGE,
            "loop" to Kind.LOOP,
            "merges" to Kind.MERGE,
            "message" to Kind.MESSAGE,
            "metadata" to Kind.METADATA,
            "nonunique" to Kind.NONUNIQUE,
            "not" to Kind.NOT,
            "objective" to Kind.OBJECTIVE,
            "occurrence" to Kind.OCCURRENCE,
            "of" to Kind.OF,
            "or" to Kind.OR,
            "ordered" to Kind.ORDERED,
            "out" to Kind.OUT,
            "package" to Kind.PACKAGE,
            "parallel" to Kind.PARALLEL,
            "part" to Kind.PART,
            "perform" to Kind.PERFORM,
            "port" to Kind.PORT,
            "private" to Kind.PRIVATE,
            "protected" to Kind.PROTECTED,
            "public" to Kind.PUBLIC,
            "readonly" to Kind.READONLY,
            "redefines" to Kind.REDEFINES,
            "ref" to Kind.REF,
            "references" to Kind.REFERENCES,
            "render" to Kind.RENDER,
            "rendering" to Kind.RENDERING,
            "rep" to Kind.REP,
            "require" to Kind.REQUIRE,
            "requirement" to Kind.REQUIREMENT,
            "return" to Kind.RETURN,
            "satisfy" to Kind.SATISFY,
            "send" to Kind.SEND,
            "snapshot" to Kind.SNAPSHOT,
            "specializes" to Kind.SPECIALIZES,
            "stakeholder" to Kind.STAKEHOLDER,
            "state" to Kind.STATE,
            "subject" to Kind.SUBJECT,
            "subsets" to Kind.SUBSETS,
            "succession" to Kind.SUCCESSION,
            "terminate" to Kind.TERMINATE,
            "then" to Kind.THEN,
            "timeslice" to Kind.TIMESLICE,
            "to" to Kind.TO,
            "transition" to Kind.TRANSITION,
            "true" to Kind.TRUE,            // missing in standard?
            "until" to Kind.UNTIL,
            "use" to Kind.USE,
            "variant" to Kind.VARIANT,
            "variation" to Kind.VARIATION,
            "verification" to Kind.VERIFICATION,
            "verify" to Kind.VERIFY,
            "via" to Kind.VIA,
            "view" to Kind.VIEW,
            "viewpoint" to Kind.VIEWPOINT,
            "when" to Kind.WHEN,
            "while" to Kind.WHILE,
            "xor" to Kind.XOR,
        ) + additionalKeywords

        val keywords = hashMapOf(
            "about" to Kind.ABOUT,
            "abstract" to Kind.ABSTRACT,
            "accept" to Kind.ACCEPT,
            "action" to Kind.ACTION,
            "actor" to Kind.ACTOR,
            "alias" to Kind.ALIAS,
            "all" to Kind.ALL,
            "allocation" to Kind.ALLOCATION,    // SysML
            "allocate" to Kind.ALLOCATE,
            "and" to Kind.AND,
            "assert" to Kind.ASSERT,
            "assoc" to Kind.ASSOC,
            "assume" to Kind.ASSUME,
            "attribute" to Kind.ATTRIBUTE,
            "behavior" to Kind.BEHAVIOR,
            "binding" to Kind.BINDING,
            "bool" to Kind.BOOL,
            "by" to Kind.BY,
            "calc" to Kind.CALC,                // SysML
            "chains" to Kind.CHAINS,
            "class" to Kind.CLASS,
            "classifier" to Kind.CLASSIFIER,
            "comment" to Kind.COMMENT,
            "composite" to Kind.COMPOSITE,
            "conjugation" to Kind.CONJUGATION,
            "conjugate" to Kind.CONJUGATE,
            "conjugates" to Kind.CONJUGATES,
            "connect" to Kind.CONNECT,
            "connection" to Kind.CONNECTION,
            "connector" to Kind.CONNECTOR,
            "constraint" to Kind.CONSTRAINT,    // SysML
            "cross" to Kind.CROSS,
            "datatype" to Kind.DATATYPE,        // KerML
            "decision" to Kind.DECISION,        // SysML
            "def" to Kind.DEF,                  // SysML
            "default" to Kind.DEFAULT,
            "dependency" to Kind.DEPENDENCY,
            "derived" to Kind.DERIVED,
            "differences" to Kind.DIFFERENCES,
            "disjoining" to Kind.DISJOINING,
            "disjoint" to Kind.DISJOINT,
            "do" to Kind.DO,
            "doc" to Kind.DOC,
            "dot" to Kind.DOTProduct,
            "else" to Kind.ELSE,
            "end" to Kind.END,
            "entry" to Kind.ENTRY,
            "enum" to Kind.ENUM,
            "exit" to Kind.EXIT,
            "expr" to Kind.EXPR,
            "false" to Kind.FALSE,
            "feature" to Kind.FEATURE,
            "featured" to Kind.FEATURED,
            "first" to Kind.FIRST,
            "flow" to Kind.FLOW,
            "for" to Kind.FOR,
            "fork" to Kind.FORK,
            "frame" to Kind.FRAME,
            "from" to Kind.FROM,
            "function" to Kind.FUNCTION,
            "hasA" to Kind.HAS_A,
            "hastype" to Kind.HASTYPE,
            "in" to Kind.IN,
            "individual" to Kind.INDIVIDUAL,
            "inout" to Kind.INOUT,
            "inverse" to Kind.INVERSE,
            "istype" to Kind.ISTYPE,
            "interaction" to Kind.INTERACTION,
            "inv" to Kind.INV,
            "isA" to Kind.SPECIALIZES,          // SysMD
            "item" to Kind.ITEM,
            "import" to Kind.IMPORT,
            "interface" to Kind.INTERFACE,
            "language" to Kind.LANGUAGE,
            "library" to Kind.LIBRARY,
            "metaclass" to Kind.METACLASS,
            "metadata" to Kind.METADATA,
            "namespace" to Kind.NAMESPACE,
            "nonunique" to Kind.NONUNIQUE,
            "not" to Kind.NOT,
            "occurrence" to Kind.OCCURRENCE,
            "of" to Kind.OF,                    // SysML
            "or" to Kind.OR,
            "out" to Kind.OUT,
            "ordered" to Kind.ORDERED,
            "perform" to Kind.PERFORM,          // SysML
            "port" to Kind.PORT,                // SysML
            "portion" to Kind.PORTION,
            "predicate" to Kind.PREDICATE,
            "private" to Kind.PRIVATE,
            "protected" to Kind.PROTECTED,
            "public" to Kind.PUBLIC,
            "readonly" to Kind.READONLY,
            "redefines" to Kind.REDEFINES,
            "ref" to Kind.REF,                  // SysML
            "references" to Kind.REFERENCES,
            "relationship" to Kind.RELATIONSHIP,
            "rep" to Kind.REP,
            "requirement" to Kind.REQUIREMENT,
            "require" to Kind.REQUIRE,
            "satisfy" to Kind.SATISFY,
            "send" to Kind.SEND,
            "snapshot" to Kind.SNAPSHOT,
            "specialization" to Kind.SPECIALIZATION,
            "stakeholder" to Kind.STAKEHOLDER,
            "standard" to Kind.STANDARD,
            "state" to Kind.STATE,
            "step" to Kind.STEP,
            "struct" to Kind.STRUCT,
            "structure" to Kind.STRUCTURE,
            "subject" to Kind.SUBJECT,
            "subsets" to Kind.SUBSETS,
            "succession" to Kind.SUCCESSION,
            "subtype" to Kind.SUBTYPE,
            "timeslice" to Kind.TIMESLICE,
            "transition" to Kind.TRANSITION,
            "true" to Kind.TRUE,
            "to" to Kind.TO,
            "type" to Kind.TYPE,
            "typed" to Kind.TYPED,
            "one" to Kind.ONE,
            "if" to Kind.IF,
            "intersects" to Kind.INTERSECTS,
            "then" to Kind.THEN,
            "specializes" to Kind.SPECIALIZES,
            "unique" to Kind.UNIQUE,
            "unions" to Kind.UNIONS,
            "package" to Kind.PACKAGE,
            "part" to Kind.PART,
            "variation" to Kind.VARIATION,
            "view" to Kind.VIEW,
            "message" to Kind.MESSAGE,
            "return" to Kind.RETURN,
        )

        val sysMDKeywords = kerMLKeywords + hashMapOf(
            "hasA" to Kind.HAS_A,
            "isA" to Kind.SPECIALIZES,
            "defines" to Kind.DEFINES
        )
    }
}
