/**
 * GENERATED FILE - DO NOT EDIT.
 *
 * Generated by MissingImplementationGenerator.
 * Source: https://www.omg.org/spec/KerML/20250201/KerML.xmi
 * Source: https://www.omg.org/spec/SysML/20250201/SysML.xmi
 * Version: 20250201
 *
 * Any manual changes will be lost the next time the generator is executed.
 */

package com.github.tukcps.sysmd.model.sysml.implementation

import com.github.tukcps.sysmd.model.expression.Expression
import com.github.tukcps.sysmd.model.kerml.Feature
import com.github.tukcps.sysmd.model.sysml.AssignmentActionUsage
import com.github.tukcps.sysmd.services.session.Session
import kotlin.uuid.Uuid

class AssignmentActionUsageImplementation(
    model : Session,
    elementId : Uuid = Uuid.random()
) : ActionUsageImplementation(model,elementId = elementId),
    AssignmentActionUsage {
    
    val referent: Feature = TODO()
    val targetArgument: Expression? = TODO()
    val valueExpression: Expression? = TODO()
    
}
