/**
 * GENERATED FILE - DO NOT EDIT.
 *
 * Generated by MissingImplementationGenerator.
 * Source: https://www.omg.org/spec/KerML/20250201/KerML.xmi
 * Source: https://www.omg.org/spec/SysML/20250201/SysML.xmi
 * Version: 20250201
 *
 * Any manual changes will be lost the next time the generator is executed.
 */

package com.github.tukcps.sysmd.model.sysml.implementation

import com.github.tukcps.sysmd.model.kerml.Element
import com.github.tukcps.sysmd.model.kerml.Type
import com.github.tukcps.sysmd.model.sysml.FlowDefinition
import com.github.tukcps.sysmd.model.sysml.Usage
import com.github.tukcps.sysmd.services.session.Session
import kotlin.uuid.Uuid

/** Suggested implementation superclass: ActionDefinitionImplementation. */
class FlowDefinitionImplementation(model : Session,elementId : Uuid = Uuid.random())
    : FlowDefinition, ActionDefinitionImplementation(model,elementId = elementId)
{
    
    val flowEnd: MutableSet<Usage> = TODO()
    override var sourceType: Type?
        get() = TODO("Not yet implemented")
        set(value) {}
    override var targetType: MutableList<Type>
        get() = TODO("Not yet implemented")
        set(value) {}
    override val associationEnd: List<Type>
        get() = TODO("Not yet implemented")

    /** The sources the relationship */
    override var source: MutableList<Element>
        get() = TODO("Not yet implemented")
        set(value) {}

    /** The targets of the relationship */
    override var target: MutableList<Element>
        get() = TODO("Not yet implemented")
        set(value) {}

    /** The owning element of this relationship */
    override var owningRelatedElement: Element
        get() = TODO("Not yet implemented")
        set(value) {}

    /** The owned elements */
    override var ownedRelatedElement: MutableList<Element>
        get() = TODO("Not yet implemented")
        set(value) {}
    override var isImplied: Boolean
        get() = TODO("Not yet implemented")
        set(value) {}

}
