@file:Suppress("FunctionName")

package com.github.tukcps.sysmd.compiler

import com.github.tukcps.sysmd.compiler.parser.sysmlv2.PackageBodyElement
import com.github.tukcps.sysmd.compiler.scanner.Token
import com.github.tukcps.sysmd.compiler.scanner.Token.Kind.EOF
import com.github.tukcps.sysmd.services.session.Session

/**
 * The SysML v2 parser's class.
 * @param model the model/session that will take the abstract elements generated by the parser
 */
class SysMLv2(
    model: Session
) : KerML(model, keywords = Token.sysMLv2Keywords) {

    override fun parse() {
        try {
            noOrMore(stop = EOF) {
                PackageBodyElement()
            }
        } catch(exception: Exception) {
            handleError(exception)
        }
    }
}