@file:Suppress("FunctionName")

package com.github.tukcps.sysmd.compiler

import com.github.tukcps.sysmd.compiler.parser.sysmlv2.PackageBodyElement
import com.github.tukcps.sysmd.compiler.scanner.Token
import com.github.tukcps.sysmd.compiler.scanner.Token.Kind.EOF
import com.github.tukcps.sysmd.compiler.semantics.UuidPolicies
import com.github.tukcps.sysmd.compiler.semantics.UuidPolicy
import com.github.tukcps.sysmd.services.session.Session
import com.github.tukcps.sysmd.services.session.SessionSettings
import com.github.tukcps.sysmd.services.session.SessionStatus
import com.github.tukcps.sysmd.services.session.implementation.SessionImplementation

/**
 * The SysML v2 parser's class.
 * @param model the model/session that will take the abstract elements generated by the parser
 * @param settings Settings object in which settings are maintained
 * @param status Status object in which errors are reported
 * @param uuidPolicy Object that determines ids
 */
open class SysMLv2(
    model: Session = SessionImplementation(), // Deprecated !
    status: SessionStatus = model.status,
    settings: SessionSettings = model.settings,
    uuidPolicy : UuidPolicy = UuidPolicies.NewSysMD
) : KerML(
    model = model,
    status = status,
    settings = settings,
    uuidPolicy = uuidPolicy,
    keywords = Token.sysMLv2Keywords
) {

    override fun parse() {
        try {
            noOrMore(stop = EOF) {
                PackageBodyElement()
            }
        } catch(exception: Exception) {
            handleError(exception)
        }
    }
}