package com.github.tukcps.sysmd.compiler.semantics

import com.github.tukcps.sysmd.compiler.KerML
import com.github.tukcps.sysmd.compiler.scanner.Token
import com.github.tukcps.sysmd.compiler.semantics.kerml.ElementAction
import com.github.tukcps.sysmd.compiler.semantics.kerml.RootNamespaceAction
import com.github.tukcps.sysmd.compiler.semantics.kerml.TypeAction
import com.github.tukcps.sysmd.exceptions.SemanticError
import com.github.tukcps.sysmd.model.datamodel.*
import com.github.tukcps.sysmd.model.expression.AstNode
import com.github.tukcps.sysmd.model.expression.functions.*
import com.github.tukcps.sysmd.model.generated.ElementType
import com.github.tukcps.sysmd.model.kerml.Feature
import com.github.tukcps.sysmd.model.kerml.Import
import com.github.tukcps.sysmd.model.kerml.Namespace
import com.github.tukcps.sysmd.model.util.QualifiedName
import com.github.tukcps.sysmd.model.util.TypeConstraint
import com.github.tukcps.sysmd.rest.entities.api.entities.Identified
import com.github.tukcps.sysmd.services.session.SessionStatus
import kotlin.uuid.Uuid

/**
 * This class provides methods that help building the ownership hierarchy of a KerML metamodel.
 * It interacts with semantic actions, for which it provides some context informatoin that limits the need
 * for passing parameters.
 * It maintains for this purpose:
 * - the current semantic action.
 * - the current element via the semantic action (for convenience)
 * - the owning element that must be set by the semantic actions. It must be null for the root namespace.
 * Parameters are:
 *
 * @param compiler the compiler that is used (KerML, SysML v2, SysMD script)
 * @param status data structure, where results of the compiler are added
 */
open class ActionsContext(
    val compiler: KerML,
    val status: SessionStatus = compiler.status
) {
    /**
     * The action that is currently being parsed.
     * Having at least the RootNamespace prevents many nullable types.
     */
    var action: ElementAction = RootNamespaceAction(this)

    /**
     * The element that is currently built by the semantic action.
     * Just a getter into the semantic action that owns it.
     */
    val element: ElementData
        get() = action.element

    /** Constructs a reference to the current element */
    val elementReference : Identified get() = when(val action = this.action) {
        is RootNamespaceAction -> when(val qn = action.qualifiedName) {
            null -> IdentifiedImplementation(null)
            else -> IdentifiedByName(name = qn, resolvesTo = IdentificationKind.Namespace)
        }
        else -> IdentifiedImplementation(element.elementId)
    }

    /** Whether [element] is the root namespace or not.
     * A non-null ownerPrefix indicates that
     * */
    val elementIsRoot get() = action.let { it is RootNamespaceAction && it.qualifiedName === null }

    /**
     * Sets declared name and shortName of the element.
     * @param name the declared name
     * @param shortName the declared short name
     */
    fun setIdentification(name: String?, shortName: String?) {
        element.declaredName = name
        element.declaredShortName = shortName
    }

    /**
     * Sets path of owning element for SysMD language and notebook extensions.
     * Here, it allows compilation in the context of a given package.
     * @param ownerPrefix a string with owning package qualified name; null if RootNamespace
     */
    fun initOwningNamespaces(ownerPrefix: QualifiedName? = null) {
        (action as RootNamespaceAction).qualifiedName = ownerPrefix
    }

    /**
     * The list in which the elements built by the semantic actions are saved.
     */
    internal val elementsBuilt: MutableList<ElementData> = mutableListOf()

    /**
     * A flag in which the visibility kind is saved by the production Prefix.
     */
    internal var visibility: Import.VisibilityKind? = null

    /**
     * A set with the prefixes of the currently parsed definition or declaration.
     * Valid from start of prefixes being parsed and the first semantic actions are executed.
     */
    internal val prefixes = mutableSetOf<Token.Kind>()

    /**
     * Marker only for the generation of AST in Expressions.
     * ONLY FOR USE IN EXPRESSION !!!
     */
    @Deprecated("Session will be dropped, use will not work anyhow now. ")
    var namespace: Namespace = compiler.model.global

    /** The owning relationship that was generated by addOwnedElement() */
    var owningRelationship: ElementData? = null

    /**
     * Adds to the current element a new element together with an owning relationship.
     * @param ownedElement the element given as data model ElementData
     * @param owningRelationshipType the type of the owning relationship to be used
     * @return A pair of the generated owning relationship, and the owned element
     */
    fun addOwnedElement(ownedElement: ElementData, owningRelationshipType: ElementType): Pair<ElementData?, ElementData> {
        assert(this.element !== ownedElement) { "Tried to make element own itself" }
        val owner = elementReference
        val owned = IdentifiedImplementation(ownedElement.elementId)

        owningRelationship = when {
            elementIsRoot && !compiler.settings.includeOwningRelationshipsToRoot -> null
            else -> ElementData(
                elementId = Uuid.random(),
                type = owningRelationshipType,
                target = mutableListOf(owned.clone()),
                source = mutableListOf(owner.clone()),
                owningRelatedElement = owner.clone(),
                ownedRelatedElement = mutableListOf(owned.clone()),
                input = compiler.input,
                // fixme: these are wrong.
                ownedElement = mutableListOf(owned.clone()),
                owner = owner.clone()
            )
        }
        val rel = IdentifiedImplementation(owningRelationship?.elementId)

        ownedElement.owningRelationship = rel.clone()
        ownedElement.owningMembership = rel.clone()
        element.ownedRelationship.add(rel.clone())

        owningRelationship?.let { elementsBuilt.add(it) }
        elementsBuilt.add(ownedElement)

        return Pair(owningRelationship, ownedElement)
    }

    /**
     * Adds to the current element a new element together with an owning relationship.
     * Also adds it to the list of built elements.
     * @param ownedRelationship the relationship that is added to the current element.
     */
    fun addOwnedRelationship(ownedRelationship: ElementData) {
        // owningMembership is nullable, then we have the root namespace.
        element.ownedRelationship.add(IdentifiedImplementation(ownedRelationship.elementId))

        // fixme: likely wrong, as relationships only have (owner !== null) if they are owned via OwningMembership
        if (!elementIsRoot)
            ownedRelationship.owner = IdentifiedImplementation(element.elementId)

        // source links it with the owning element; null for root namespace!
        val source = elementReference
        ownedRelationship.source = mutableListOf(source)
        ownedRelationship.owningRelatedElement = source.clone()
        elementsBuilt.add(ownedRelationship)
    }

    /**
     * Adds an owned relationship to the current type, e.g., a specialization, type-featuring.
     * @param target the target of the owned relationship, identified by name or id.
     * @param type the type of the owned relationship to be generated.
     */
    fun addOwnedRelationship(target: Identified, type: ElementType) {
        val action = action

        if (action is TypeAction) {
            action.superTypeDefined = true
            val source = elementReference

            val ownedRelationship = ElementData(
                elementId = Uuid.random(),
                type = type,
                source = mutableListOf(source),
                target = mutableListOf(target),
                owningRelatedElement = source.clone(),

                owner = source.clone() // fixme: wrong.
            )
            action.element.ownedRelationship.add(IdentifiedImplementation(ownedRelationship.elementId))
            elementsBuilt.add(ownedRelationship)
        } else
            status.fatal("Internal issue: owner of addOwnedRelationship must be a type")
    }

    /**
     * Adds an owned unioning relationship.
     * @param type the name of the type, as in the source code
     */
    fun addUnioning(type: QualifiedName) =
        addOwnedRelationship(compiler.typeByName(type), ElementType.Unioning)

    /**
     * Adds an owned differencing relationship.
     * @param type the name of the type, as in the source code
     */
    fun addDifferencing(type: QualifiedName) =
        addOwnedRelationship(compiler.typeByName(type), ElementType.Differencing)

    /**
     * Adds an owned differencing relationship.
     * @param type the name of the type, as in the source code
     */
    fun addIntersecting(type: QualifiedName) =
        addOwnedRelationship(compiler.typeByName(type), ElementType.Intersecting)

    /**
     * Adds an owned feature typing relationship.
     * @param type the name of the type, as in the source code
     */
    fun addDisjoining(type: QualifiedName) =
        addOwnedRelationship(compiler.typeByName(type), ElementType.Disjoining)

    /**
     * Adds a typing to features.
     * @param type the type of owning feature as a Qualified Name.
     */
    fun addTyping(type: QualifiedName) =
        addOwnedRelationship(compiler.typeByName(type), ElementType.FeatureTyping)

    /**
     * Adds a ReferenceSubsetting relationship.
     * @param referencedFeature qualified name of the referenced feature
     */
    fun addReferenceSubsetting(referencedFeature: Identified) =
        addOwnedRelationship(referencedFeature, ElementType.ReferenceSubsetting)

    /**
     * Adds a ReferenceSubsetting relationship.
     * @param referencedFeature qualified name of the referenced feature
     */
    fun addReferenceSubsetting(referencedFeature: QualifiedName) =
        addOwnedRelationship(compiler.featureByName(referencedFeature), ElementType.ReferenceSubsetting)

    /**
     * Adds an owned Subclassification relationship.
     * @param type the type for which owned subclassification is created
     */
    fun addSubclassification(type: String) =
        addOwnedRelationship(compiler.typeByName(type), ElementType.Subclassification)

    /**
     * Adds a Redefinition relationship.
     * @param redefinedFeature
     */
    fun addRedefinition(redefinedFeature: QualifiedName) =
        addOwnedRelationship(compiler.featureByName(redefinedFeature), ElementType.Redefinition)
    fun addSpecialization(type: QualifiedName) =
        addOwnedRelationship(compiler.typeByName(type), ElementType.Specialization)
    fun addConjugation(conjugated: String) =
        addOwnedRelationship(compiler.typeByName(conjugated) , ElementType.Conjugation)
    fun addSubsetting(subsettedFeature: QualifiedName) =
        addOwnedRelationship(compiler.featureByName(subsettedFeature), ElementType.Subsetting)

    /**
     * Adds a reference subsetting to the feature
     * @param references, a single qualified name
     */
    fun addReferences(references: QualifiedName?) {
        if (references != null) {
            addReferenceSubsetting(referencedFeature = references)
        }
    }

    /**
     * Adds a sequence of redefinition
     */
    fun addRedefinitions(redefines: MutableList<String>) {
        if (element.declaredName == null && element.declaredShortName == null)
            element.declaredName = redefines.firstOrNull()
        redefines.forEach {
            addRedefinition(it)
        }
    }

    /**
     * Adds a constraint on the unit of the element on top of the owner stack.
     * @param unitConstraint the unit expected.
     */
    fun addUnitConstraint(unitConstraint: String?) {
        if (compiler.settings.addConstraints)
            if (unitConstraint != null) {
                addOwnedElement(
                    ElementData(
                        elementId = Uuid.random(),
                        type = ElementType.Feature,
                        declaredName = "unit",
                        body = unitConstraint
                    ),
                    ElementType.FeatureMembership
                )
            }
    }

    /**
     * Generates a Features with an expression that acts as constraint for the range
     * of an owning type.
     * @param typeConstraint the constraint that is added to the type definition.
     */
    fun addTypeConstraint(typeConstraint: TypeConstraint) {
        if (compiler.settings.addConstraints && typeConstraint.value.isNotEmpty())
        {
            addOwnedElement(
                ElementData(
                    elementId = Uuid.random(),
                    type = ElementType.Feature,
                    declaredName = "range",
                    body = typeConstraint.toString()
                ),
                ElementType.FeatureMembership
            )
        }
    }

    fun setSource(source: Identified) {
        element.source = mutableListOf(source)
    }

    fun addSource(source: Identified) {
        element.source.add(source)
    }

    fun setTarget(target: Identified) {
        element.target = mutableListOf(target)
    }

    fun addTarget(target: Identified) {
        element.target.add(target)
    }

    fun setSourceEnd(source: ElementData) {
        element.source = mutableListOf(IdentifiedImplementation(source.elementId))
    }

    fun setSourceEnd(name: QualifiedName) {
        element.source = mutableListOf(IdentifiedByName(name = name, resolvesTo = IdentificationKind.Element))
    }

    fun setTargetEnd(target: QualifiedName) {
        element.target = mutableListOf(IdentifiedByName(target, resolvesTo = IdentificationKind.Element))
    }

    fun addTargetEnd(target: ElementData) = element.target.add(IdentifiedImplementation(target.elementId))

    fun setTargetEnd(target: ElementData) {
        element.target = mutableListOf(IdentifiedImplementation(target.elementId))
    }

    fun directionFromPrefixes(): Feature.FeatureDirectionKind? = when {
        Token.Kind.IN in prefixes -> Feature.FeatureDirectionKind.IN
        Token.Kind.OUT in prefixes -> Feature.FeatureDirectionKind.OUT
        Token.Kind.INOUT in prefixes -> Feature.FeatureDirectionKind.INOUT
        else -> null
    }

    /**
     * @method mkFuncCall
     * @detail This method builds the expression tree for a function call.
     * It sets the parameters of a function into the local symbol table.
     * @param function name of the function to be called
     * @param param of the function as an ArrayList of AstNode
     * @return The Expression tree
     * @throws SemanticError
     */
    fun handleFunctionCall(function: QualifiedName, param: ArrayList<AstNode>, semantics: ActionsContext): AstNode {
        val model = compiler.model
        val namespace = this.namespace
        return when (function) {
            "owns" -> AstHasA(model, param, semantics)
            "ITE" -> AstIte(model, param)
            "oneOf" -> buildOneOfAst(model, param, semantics)
            "allOf" -> AstAllOf(model, param)
            "anyOf" -> AstAnyOf(model, param)
            "sum_i" -> AstSumI(namespace, model, param)
            "sum" -> AstSum(namespace, model, param)
            "sumOverParts" -> AstSumOverParts(model, namespace, param, transitive = true)
            "sumOverSubclasses" -> AstSumOverSubclasses(model, namespace, param, transitive = true)
            "productOverParts" -> AstProductOverParts(model, namespace, param, transitive = true)
            "productOverSubclasses" -> AstProductOverSubclasses(model, namespace, param, transitive = true)
            "sumOverPartsNotTransitive" -> AstSumOverParts(model, namespace, param, transitive = false)
            "sumOverSubclassesNotTransitive" -> AstSumOverSubclasses(model, namespace, param, transitive = false)
            "productOverPartsNotTransitive" -> AstProductOverParts(model, namespace, param, transitive = false)
            "productOverSubclassesNotTransitive" -> AstProductOverSubclasses(model, namespace, param, transitive = false)
            "characterizedResult" -> AstCharacterizedResult(model, namespace, param)
            "ln" -> AstLn(model, param)
            "exp" -> AstExp(model, param)
            "sqr" -> AstSqr(model, param)
            "sqrt" -> AstSqrt(model, param)
            "ceil" -> AstCeil(model, param)
            "floor" -> AstFloor(model, param)
            "power2" -> AstPower2(model, param)
            "pow2" -> AstPower2(model, param)
            "powerb" -> AstPower(model, param)
            "power" -> AstPower(model, param)
            "powb" -> AstPower(model, param)
            "pow" -> AstPower(model, param)
            "sin" -> AstSin(model,param)
            "cos" -> AstCos(model,param)
            "toReal" -> AstToReal(model, param)
            "DateTime" -> AstDateTime(model, param)
            "Date" -> AstDate(model, param)
            "Month" -> AstMonth(model, param)
            "Year" -> AstYear(model, param)
            "max" -> AstMax(model, param)
            "min" -> AstMin(model, param)
            "abs" -> AstAbs(model, param)
            "intersect" -> AstIntersect(model, param)
            "bySpecializations" -> AstBySpecializations(model, namespace, param)
            "byParts" -> AstByParts(model, namespace, param)
            "byImplements" -> AstByImplements(model, namespace, param)
            "linearInterpolation" -> AstLinearInterpolation(model, param)
            "stepInterpolation" -> AstStepInterpolation(model,param)
            "ToReal" -> AstReal(model, param)
            "ToInteger" -> AstInteger(model, param)
            "norm" -> AstNormalizeVector(model,param)
            "size" -> AstVectorSize(model, param)
            "angle" -> AstVectorAngle(model,param)
            "cityBlockDistance" -> AstCityBlockDistance(model,param)
            "quantityOfVectorAtPosition" -> AstQuantityOfVectorAtPosition(model,param)
            else -> AstUserDefinedFunction(model,namespace, param, function)
        }
    }
}
