package constraintnettests

class CspSolverEvalUpTest {
    /*
    @Test
    fun testConstraintNetAlgorithm() = testSession("ScalarValues") {
            defVar("a", builder.range(0.99, 1.01, "a"))
            defVar("b", builder.range(1.99, 2.01, "b"))
            defVar("c", builder.range(2.99, 3.01, "c"))
            defVar("d", builder.range(3.99, 4.01, "d"))
            defVar("ee", builder.range(1.99, 2.01, "ee"))
            +"Global hasA y: Real = a-b+c*d/ee"
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            letVar("a", builder.range(0.98, 1.00, "a"))
            val solver = CspSolver(this)
            solver.evalFromVar(resolveName("y")!!, "a")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("a", builder.range(1.00, 1.02, "a"))
            CspSolver(this).evalFromVar(resolveName("y")!!, "a")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("a", builder.range(0.98, 1.02, "a"))
            CspSolver(this).evalFromVar(resolveName("y")!!, "a")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("a", builder.range(0.97, 0.99, "a"))
            CspSolver(this).evalFromVar(resolveName("y")!!, "a")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("a", builder.range(1.02, 1.04, "a"))
            CspSolver(this).evalFromVar(resolveName("y")!!, "a")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("a", builder.range(0.96, 1.04, "a"))
            CspSolver(this).evalFromVar(resolveName("y")!!, "a")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("b", builder.range(1.99, 2.02, "b"))
            CspSolver(this).evalFromVar(resolveName("y")!!, "b")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("b", builder.range(1.98, 2.01, "b"))
            CspSolver(this).evalFromVar(resolveName("y")!!, "b")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("b", builder.range(1.96, 1.98, "b"))
            CspSolver(this).evalFromVar(resolveName("y")!!, "b")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("b", builder.range(2.02, 2.04, "b"))
            CspSolver(this).evalFromVar(resolveName("y")!!, "b")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("b", builder.range(1.96, 2.04, "b"))
            CspSolver(this).evalFromVar(resolveName("y")!!, "b")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("c", builder.range(2.99, 3.02, "c"))
            CspSolver(this).evalFromVar(resolveName("y")!!, "c")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("c", builder.range(2.98, 3.01, "c"))
            CspSolver(this).evalFromVar(resolveName("y")!!, "c")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("c", builder.range(2.96, 2.98, "c"))
            CspSolver(this).evalFromVar(resolveName("y")!!, "c")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("c", builder.range(3.02, 3.04, "c"))
            CspSolver(this).evalFromVar(resolveName("y")!!, "c")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("c", builder.range(2.96, 3.04, "c"))
            CspSolver(this).evalFromVar(resolveName("y")!!, "c")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("d", builder.range(3.99, 4.02, "d"))
            solver.evalFromVar(resolveName("y")!!, "d")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("d", builder.range(3.98, 4.01, "d"))
            solver.evalFromVar(resolveName("y")!!, "d")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("d", builder.range(3.96, 3.98, "d"))
            solver.evalFromVar(resolveName("y")!!, "d")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("d", builder.range(4.02, 4.04, "d"))
            solver.evalFromVar(resolveName("y")!!, "d")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("d", builder.range(3.96, 4.04, "d"))
            solver.evalFromVar(resolveName("y")!!, "ee")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("ee")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("ee")!!.aadd().getRange().max, 0.1)
            letVar("ee", builder.range(1.99, 2.02, "ee"))
            solver.evalFromVar(resolveName("y")!!, "ee")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            letVar("ee", builder.range(1.98, 2.01, "ee"))
            solver.evalFromVar(resolveName("y")!!, "ee")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            letVar("ee", builder.range(1.96, 1.98, "ee"))
            solver.evalFromVar(resolveName("y")!!, "ee")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            letVar("ee", builder.range(2.02, 2.04, "ee"))
            solver.evalFromVar(resolveName("y")!!, "ee")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
            letVar("ee", builder.range(1.96, 2.04, "ee"))
            solver.evalFromVar(resolveName("y")!!, "ee")
            Assertions.assertEquals(4.92, resolveName<ValueFeature>("y")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(5.09, resolveName<ValueFeature>("y")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(0.99, resolveName<ValueFeature>("a")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(1.01, resolveName<ValueFeature>("a")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(2.99, resolveName<ValueFeature>("c")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(3.01, resolveName<ValueFeature>("c")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(3.99, resolveName<ValueFeature>("d")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(4.01, resolveName<ValueFeature>("d")!!.aadd().getRange().max, 0.1)
            Assertions.assertEquals(1.99, resolveName<ValueFeature>("b")!!.aadd().getRange().min, 0.1)
            Assertions.assertEquals(2.01, resolveName<ValueFeature>("b")!!.aadd().getRange().max, 0.1)
    } */
}